@echo off
set MATLAB=C:\PROGRA~1\MATLAB\R2017a
set MATLAB_ARCH=win64
set MATLAB_BIN="C:\Program Files\MATLAB\R2017a\bin"
set ENTRYPOINT=mexFunction
set OUTDIR=.\
set LIB_NAME=SOLVER_LINEAR_VLM_mex
set MEX_NAME=SOLVER_LINEAR_VLM_mex
set MEX_EXT=.mexw64
call "C:\PROGRA~1\MATLAB\R2017a\sys\lcc64\lcc64\mex\lcc64opts.bat"
echo # Make settings for SOLVER_LINEAR_VLM > SOLVER_LINEAR_VLM_mex.mki
echo COMPILER=%COMPILER%>> SOLVER_LINEAR_VLM_mex.mki
echo COMPFLAGS=%COMPFLAGS%>> SOLVER_LINEAR_VLM_mex.mki
echo OPTIMFLAGS=%OPTIMFLAGS%>> SOLVER_LINEAR_VLM_mex.mki
echo DEBUGFLAGS=%DEBUGFLAGS%>> SOLVER_LINEAR_VLM_mex.mki
echo LINKER=%LINKER%>> SOLVER_LINEAR_VLM_mex.mki
echo LINKFLAGS=%LINKFLAGS%>> SOLVER_LINEAR_VLM_mex.mki
echo LINKOPTIMFLAGS=%LINKOPTIMFLAGS%>> SOLVER_LINEAR_VLM_mex.mki
echo LINKDEBUGFLAGS=%LINKDEBUGFLAGS%>> SOLVER_LINEAR_VLM_mex.mki
echo MATLAB_ARCH=%MATLAB_ARCH%>> SOLVER_LINEAR_VLM_mex.mki
echo BORLAND=%BORLAND%>> SOLVER_LINEAR_VLM_mex.mki
echo OMPFLAGS= >> SOLVER_LINEAR_VLM_mex.mki
echo OMPLINKFLAGS= >> SOLVER_LINEAR_VLM_mex.mki
echo EMC_COMPILER=lcc64>> SOLVER_LINEAR_VLM_mex.mki
echo EMC_CONFIG=optim>> SOLVER_LINEAR_VLM_mex.mki
"C:\Program Files\MATLAB\R2017a\bin\win64\gmake" -B -f SOLVER_LINEAR_VLM_mex.mk
